[package]
name = "grib2sail-cli"
description = "CLI wrapper for the grib2sail downloader"
version = "0.7.2"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/Ch1nkara/GRIB2Sail"
readme = "../README.md"

[[bin]]
name = "grib2sail-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
grib2sail = { path = "../grib2sail" }
chrono = "0.4.43"
clap = { version = "4.5.57", features = ["derive"] }
colored = "3.1.1"
indicatif = "0.18.3"
keyring = { version = "3.6.3", features = [
  "sync-secret-service", "vendored", "crypto-rust",
  "windows-native",
  "apple-native"
] }
log = "0.4.29"
once_cell = "1.21.3"
reqwest = "0.13.2"
self_update = { version = "0.42.0", features = [
  "archive-tar", "compression-flate2",
  "archive-zip", "compression-zip-deflate", "compression-zip-bzip2"
] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
