FROM rust:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libssl-dev \
    ca-certificates \
    git \
  && rustup component add rustfmt clippy \
  && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash vscode
USER vscode
WORKDIR /workspaces/Grib2Sail
CMD ["sleep", "infinity"]
