FROM rust:bookworm

ENV DEBIAN_FRONTEND=noninteractive \
    CARGO_TERM_COLOR=always

RUN apt-get update && apt-get install -y --no-install-recommends \
        pkg-config \
        libdbus-1-dev \
        clang \
        lldb \
    && rm -rf /var/lib/apt/lists/* \
    && rustup component add rustfmt clippy rust-analyzer \
    && cargo install bacon \
    && chmod -R a+rwX /usr/local/cargo /usr/local/rustup

RUN useradd -mU -s /bin/bash dev
USER dev
